inherit_from: .rubocop_todo.yml
# require:
#   - rubocop-rspec

# Style

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/HashSyntax:
  EnforcedStyle: ruby19

Style/RescueStandardError:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/PreferredHashMethods:
  EnforcedStyle: verbose

# Layout

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/BlockAlignment:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line

# RSpec

# RSpec/NamedSubject:
#   Enabled: false

# RSpec/InstanceVariable:
#   Enabled: false

# RSpec/FilePath:
#   Enabled: false

# Metrics

Metrics/LineLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Max: 150

Metrics/BlockLength:
  Max: 250

Metrics/MethodLength:
  Max: 30

Metrics/ParameterLists:
  CountKeywordArgs: false

AllCops:
  TargetRubyVersion: 2.7.0
